version: '3'

networks:
  nginx_network:
    driver: bridge
  wg_network:
    external: true

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    networks:
      - nginx_network
    # ports:
    #   - "8080:80"
    expose:
      - 8000
    volumes:
      - ./site1:/usr/share/nginx/html/site1
      - ./site1/default.conf:/etc/nginx/conf.d/default.conf
      - ./site1/ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./site1/ssl/key.pem:/etc/nginx/conf.d/key.pem
      - ./site1/ssl/pass.txt:/etc/nginx/conf.d/pass.txt
  nginx2:
    image: nginx:latest
    container_name: nginx2
    networks:
      - nginx_network
    # ports:
    #   - "8081:80"
    expose:
      - 9000
    volumes:
      - ./site2:/var/www
      - ./site2/default.conf:/etc/nginx/conf.d/default.conf
      - ./site2/ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./site2/ssl/key.pem:/etc/nginx/conf.d/key.pem
      - ./site2/ssl/pass.txt:/etc/nginx/conf.d/pass.txt
  nginx3:
    image: nginx:latest
    container_name: nginx3
    networks:
      - nginx_network
    ports:
      - "8445:443"
      - "8585:80"
    volumes:
      - ./ProxyNginx:/usr/share/nginx/html/main
      - ./ProxyNginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ProxyNginx/ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ProxyNginx/ssl/key.pem:/etc/nginx/conf.d/key.pem
      - ./ProxyNginx/ssl/pass.txt:/etc/nginx/conf.d/pass.txt

  nginx-php:
      build:
          context: .
          dockerfile: ./site-php/Dockerfile
      container_name: nginx-php
      restart: unless-stopped
      tty: true
      environment:
          SERVICE_NAME: nginx-php
          SERVICE_TAGS: dev
      volumes:
          - ./site-php:/var/www
      networks:
          - nginx_network

  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - nginx_network
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_DATABASE: feedback
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped